/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800
#define RCC_APB2ENR	*((volatile uint32_t*)(RCC_BASE+0x18))
#define GPIO_CRH	*((volatile uint32_t*)(GPIOA_BASE+0x04))
#define GPIO_ODR	*((volatile uint32_t*)(GPIOA_BASE+0x0c))

typedef union{
	volatile uint32_t all_fields;
	struct{
		volatile uint32_t reserved:13;
		volatile uint32_t P_13:1;
	}SPin;
}SRODR_t;
volatile SRODR_t* R_ODR = (volatile SRODR_t*)(GPIOA_BASE+0x0c);

int main(void)
{
	int32_t i;
	RCC_APB2ENR |= 1<<2;
	GPIO_CRH &= 0xFF0FFFFF;
	GPIO_CRH |= 0x00200000;
	/* Loop forever */
	while(1)
	{
		R_ODR -> SPin.P_13 = 1;
		for(i=0;i<5000;i++);
		R_ODR -> SPin.P_13 = 0;
		for(i=0;i<5000;i++);
	}
	return 0;
}
